spring.datasource:
  url: jdbc:postgresql://localhost:5432/micro3
  username: igor
  password: 123456
spring.jpa:
  properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  show-sql: true
  properties.hibernate.format_sql: true

server.port: 8081

spring.cloud.function.definition: consumeMessage

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.consumeMessage-in-0:
    destination: inventory
    group: inventoriesGroup

spring.cloud.stream.bindings.consumeMessage-in-0.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.consumeMessage-in-0.consumer:
  autoBindDlq: true
  republishToDlq: true
  
spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest
  
---
spring.config.activate.on-profile: docker

spring.rabbitmq:
  host: message
